### ISSUE TITLE
Please provide a minimal example

### ISSUE THREAD

**Issue by mvoss96** [khoih-prog/ESPAsync_WiFiManager_Lite#1]
Hi, I would like to integrate your library into my project, but I am struggling to parse through the provided example.
Could you provide a minimal example how to use this library?

**Comment by khoih-prog** [comment]
Please go through the examples and try to understand, then minimize them according to your use case.

This will benefit you in the long run than just use it, without fully understanding. I used to compare to the `fast food` metaphor.

Good Luck,

**Comment by thenicnic** [comment]
Thank you for your outstanding work, but I think a minimal config for at least the "LOAD_DEFAULT_CONFIG_DATA" and "defaultConfig" thing would be cool. Have no idea to configure to leave out the default config credentials and to just show up the AP captive portal if there aren't valid credentials in the SPIFFS.

As you know, compiling and debugging each time takes a few seconds and breaking down a few project files of code isn't 
what to expect from a "Lite" WiFi manager IMHO. And if I don't edit all the example files, my code gets really huge.

**Comment by thenicnic** [comment]
OK got it working in base config now:
```
ESPAsync_WiFiManager_Lite* ESPAsync_WiFiManager;
#define USE_DYNAMIC_PARAMETERS      false
#define SCAN_WIFI_NETWORKS          true
#define REQUIRE_ONE_SET_SSID_PW     true
bool LOAD_DEFAULT_CONFIG_DATA = false;

ESP_WM_LITE_Configuration defaultConfig = {};
```

SSID: _ESP__[YOURESPID]
PW: _MyESP__[YOURESPID]

But I need to enter two APs although "REQUIRE_ONE_SET_SSID_PW" is set to "true" and the captive portal doesn't show up on my smartphone automatically. Will see if it get this fixed.

**Comment by khoih-prog** [comment]
I'm glad that you're doing good with your project.
If you need any advice, I'll help, certainly only after you have done some work.

**Comment by mvoss96** [comment]
> Thank you for your outstanding work, but I think a minimal config for at least the "LOAD_DEFAULT_CONFIG_DATA" and "defaultConfig" thing would be cool. Have no idea to configure to leave out the default config credentials and to just show up the AP captive portal if there aren't valid credentials in the SPIFFS.
> 
> As you know, compiling and debugging each time takes a few seconds and breaking down a few project files of code isn't
> what to expect from a "Lite" WiFi manager IMHO. And if I don't edit all the example files, my code gets really huge.

Hi, Sadly i couldn't get this library to work in my own code, so I ended up using the non lite espasyncwifimanager. I found this example very understandable: https://github.com/khoih-prog/ESPAsync_WiFiManager/blob/master/examples/Async_ConfigOnDRD_ESP8266_minimal/Async_ConfigOnDRD_ESP8266_minimal.ino
