### ISSUE TITLE
No config page loading

### ISSUE THREAD

**Issue by InfospyPT** [khoih-prog/ESPAsync_WiFiManager_Lite#10]
Followed the examples.

Using PlatformIO with Core 6x
Board starts, WiFi AP shows up, and I can connect with password,

When I connect my phone to the network and then try to reach the IP Address, I get no page.

Any idea?

I get this warning:

In file included from src/defines.h:73,
                 from src/Credentials.h:4,
                 from src/main.cpp:1:
.pio/libdeps/az-delivery-devkit-v4/ESPAsync_WiFiManager_Lite/src/ESPAsync_WiFiManager_Lite.h:133:8: warning: #warning Using ESP32 Core 1.0.6 or 2.0.0+ [-Wcpp]
       #warning Using ESP32 Core 1.0.6 or 2.0.0+

Terminal output on Upload and Monitor:

Starting ESPAsync_WiFi using LittleFS ON AZ-Delivery ESP-32 Dev Kit C V4
ESPAsync_WiFiManager_Lite v1.9.0
ESP_MultiResetDetector v1.3.2
[   483][E][vfs_api.cpp:104] open(): /littlefs/wm_config.dat does not exist, no permits for creation
[   487][E][vfs_api.cpp:104] open(): /littlefs/wm_config.bak does not exist, no permits for creation
[WML] WiFi networks found:
[WML] 1: PrettyFlyForAWiFi, -38dB
[WML] 
stConf:SSID=ESP_5270E0,PW=MyESP_5270E0
[WML] IP=192.168.4.1,ch=3
C

**Comment by khoih-prog** [comment]
Hi @InfospyPT 

First try to compile / run your code in Arduino IDE to see if OK. If OK, then move to **PIO**, which requires **more experience, manual settings, and knowledge.**

If only PIO creates problem, research more about PIO or post the issue on **PIO Forum**

Anywhere, you have to post [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example), or your post will be ignored / deleted.

I'm closing this now and won't open until you have done your minimal **homework** and  **prove this is a reproducible bug of this library.**

---

Also check why your **LittleFS** isn't working by testing the minimal **LittleFS** code.

1. [**Unable to figure out why 'LittleFS' was not declared in this scope** #96](https://github.com/khoih-prog/ESPAsync_WiFiManager/discussions/96)
2. [**fatal error: vfs_api.h: No such file or directory** #11](https://github.com/khoih-prog/ESP_WiFiManager_Lite/issues/11#issuecomment-1190526303)

**Comment by InfospyPT** [comment]
Thanks.
I actually tested from another device and it actually connected to the page. The problem seems to be how my android handles connecting to an AP without internet access.

I noticed, though, that the custom Header and custom styles functions aren't define, although present in the examples.

Any idea there?

**Comment by khoih-prog** [comment]
> I noticed, though, that the custom Header and custom styles functions aren't define, although present in the examples

It's better you treat it as your minimal homework ;=}} No more time to spend here.
