### ISSUE TITLE
Add support for getTimezoneName() and getTZ(timezoneName)

### ISSUE THREAD

**Issue by benpeart** [khoih-prog/ESPAsync_WiFiManager_Lite#13]
The ESPAsync_WiFiManager library had support for exposing the timezone. I tried using the same setting:

```
// Use false to disable NTP config. Advisable when using Cellphone, Tablet to access Config Portal.
// See Issue 23: On Android phone ConfigPortal is unresponsive (https://github.com/khoih-prog/ESP_WiFiManager/issues/23)
#define USE_ESP_WIFIMANAGER_NTP     true
```

to ensure the flag was set but ESPAsync_WiFiManager_Lite doesn't appear to have the required getTimezoneName and getTZ methods.

I would appreciate this new/parity feature being added or documented if there is a way to do it that I just haven't found.

Thank you!

**Comment by khoih-prog** [comment]
Check the answer in [**The Config Portal does not automatically open after connecting to the access point** #12](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/issues/12), but this won't be added as it already created more problems even to the full-fledged [**ESPAsync_WiFiManager** library](https://github.com/khoih-prog/ESPAsync_WiFiManager)

Regards,
