### ISSUE TITLE
Not working with ESP32 Core 2.0.X because of LittleFS?

### ISSUE THREAD

**Issue by Frtrillo** [khoih-prog/ESPAsync_WiFiManager_Lite#4]
### Describe the bug

I can't use this library with ESP32 Core 2.0 or 2.0.1.
### Steps to Reproduce

Update ESP32 Core to 2.0 or 2.0.1 and compile example.

### Expected behavior

Compile and run

### Actual behavior

I get compile errors if I compile and run because of LittleFS. 
- If I install the esp32 LittleFS library (which is supposed to not be required as its included on 2.0.X core) I still get errors and warnings of use built-in library.
- If I rename all LITTLEFS words to LittleFS, my sketch compile but it wont work getting [WML] Invalid Stored WiFi Config Data errors in serial terminal. 

### Debug and AT-command log (if applicable)

EEPROM Flag read = 0xFFFE0001
SetFlag write = 0xFFFD0002
[WML] Invalid Stored WiFi Config Data

### Screenshots

![image](https://user-images.githubusercontent.com/72965099/139586261-eddb4d69-85b0-4b49-b169-dfbbc2d64493.png)

### Information

Arduino IDE version: 1.8.13
ESP32 Core Version 2.0
OS:  Windows 10

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

I think your installation has some issue, as I don't find any issue at all in compiling and running

![Selection_069](https://user-images.githubusercontent.com/57012152/139594841-210f940e-8a18-42b0-9a9c-73eeefeddee8.png)

I don't think I have to prove anything here. If you check and still have unsolved issue, I suggest you seek help in other forum ( Arduino, ESP32, etc) as **I don't have time to deal with issues not related to library bug.**

Good Luck,

**Comment by khoih-prog** [comment]
Hi @Frtrillo 

Thanks for your bug report and I now have found the bug and fix it with new release [**ESPAsync_WiFiManager_Lite releases v1.6.0**](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/releases/tag/v1.6.0)

I'm sorry to not being able to duplicate the bug previously.

---

### Release v1.6.0

1. Auto detect ESP32 core and use either built-in LittleFS or [LITTLEFS](https://github.com/lorol/LITTLEFS) library. 
2. Fix bug returning IP `255.255.255.255` in core v2.0.0+ when using `hostname`
