### ISSUE TITLE
DHCP can not work using ESP8266 core version v3.0.2

### ISSUE THREAD

**Issue by manhere** [khoih-prog/ESPAsync_WiFiManager_Lite#5]
### Describe the bug

DHCP can not work using ESP8266 core version v3.0.2

### Steps to Reproduce

use default example

### Debug and AT-command log (if applicable)

> 11:39:19.057 -> Starting ESPAsync_WiFi_MQTT using LittleFS on ESP8266_NODEMCU_ESP12E
11:39:19.091 -> ESPAsync_WiFiManager_Lite v1.5.1
11:39:19.091 -> ESP_MultiResetDetector v1.1.2
11:39:19.091 -> LittleFS Flag read = 0xFFFE0001
11:39:19.091 -> multiResetDetectorFlag = 0xFFFE0001
11:39:19.091 -> lowerBytes = 0x0001, upperBytes = 0x0001
11:39:19.091 -> No multiResetDetected, number of times = 1
11:39:19.091 -> LittleFS Flag read = 0xFFFE0001
11:39:19.125 -> Saving config file...
11:39:19.125 -> Saving config file OK
11:39:21.349 -> [WML] WiFi networks found:
11:39:21.349 -> [WML] 1: werrwe, -60dB
11:39:21.349 -> [WML] 2: TP-LINK_0FC5, -65dB
11:39:21.383 -> [WML] 3: iTV-Yvga, -88dB
11:39:22.378 -> [WML] 
11:39:22.412 -> stConf:SSID=ESP_ED5BC3,PW=MyESP_ED5BC3
11:39:22.412 -> [WML] IP=192.168.4.1,ch=10
11:39:22.481 -> N
11:39:22.481 -> Your stored Credentials :
11:39:22.481 -> AIO_SERVER = io.adafruit.com
11:39:22.516 -> AIO_SERVERPORT = 1883
11:39:22.516 -> AIO_USERNAME = private
11:39:22.516 -> AIO_KEY = private
11:39:22.516 -> AIO_PUB_TOPIC = /feeds/Temperature
11:39:22.516 -> AIO_SUB_TOPIC = /feeds/LED_Control
11:39:27.493 -> NStop multiResetDetecting
11:39:28.832 -> Saving config file...
11:39:28.832 -> Saving config file OK
11:39:32.507 -> NNN NNNNN NNNNN NNN

### Information
* Arduino IDE version 1.8.16
* ESP8266 core version v3.0.2

**Comment by khoih-prog** [comment]
HI @manhere 

Thanks for using the library.

I suggest you revert to ESP8266 core v2.7.4 if the issue persists.

You can also try

1. To use core example [**WiFiAccessPoint**](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi/examples/WiFiAccessPoint) to see if you can log into the AP
2. Reset the board to use another WiFi channel (to avoid conflict) and retry. Be sure you still keep [**ESP_WiFi_MQTT.ino#L311**](https://github.com/khoih-prog/ESP_WiFiManager_Lite/blob/main/examples/ESP_WiFi_MQTT/ESP_WiFi_MQTT.ino#L311)

```
ESPAsync_WiFiManager->setConfigPortalChannel(0);
```

I can connect to the ESP8266 AP without any issue, but sometimes having problem connecting to AP, even with the core [**WiFiAccessPoint** example](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi/examples/WiFiAccessPoint). It seems the core v3.0.0+ has some modifications / bugs that make AP connection more difficult than v2.7.4

If you still have problem using [**WiFiAccessPoint**](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi/examples/WiFiAccessPoint), you can file [an issue](https://github.com/esp8266/Arduino/issues) in the ESP8266 core.

This is not the bug of the library, so I'm closing it now.

Good Luck,
