### ISSUE TITLE
How to extend with syntax --->  server.on("/get", HTTP_GET, [](AsyncWebServerRequest *request)

### ISSUE THREAD

**Issue by we-do-it-lu** [khoih-prog/ESPAsync_WiFiManager_Lite#6]
I discovered this ‘ESPAsync_WiFiManager_Lite’ project today, I find it great; It really makes it easy connecting to WiFi in Configuration Portal Mode.
What I don’t understand is: Once my ESP32 is effectively connected to my WiFi I want it to do “something”, specifically I want it to reply to GET requests to return whatever data
If this makes sense… 
Another way to put it is once the WiFi is connected I want the module to serve AsyncWebServer on port 80 (else what the point of getting connected to the network if it’s not to serve data?)
I could I go about this? 
I tried :
`AsyncWebServer server(80);`

then 

```
server.on("/get", HTTP_GET, [](AsyncWebServerRequest *request){
      request->send(200, "text/plain", “Hello world");
});

```
But it does not work this way I think, I am confused with the various libraries. 
A little help would be great.
Thank you very much in advance.

**Comment by khoih-prog** [comment]
Have a look at [**Async_ESP32_FSWebServer_DRD** example](https://github.com/khoih-prog/ESPAsync_WiFiManager/tree/master/examples/Async_ESP32_FSWebServer_DRD) and see how to create and use AsyncWebServer in very similar case.

This [**ESPAsync_WiFiManager_Lite** instance](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite) is short-lived and is dead after fulfilling its job, which has no intended purpose to serve any other data besides the Config Portal.

Even I'm glad to see your interest in this library, I'm afraid I won't spend time to help you out, if your problem persists. 

Try to  study the  above-mentioned example
